package com.example.kind.view.theme

import androidx.compose.ui.graphics.Color

/** Colorscheme design by Tera Zwergius Teilmann Sverud **/

val md_theme_light_primary = Color(0xFF63AF6F)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFBBF293)
val md_theme_light_onPrimaryContainer = Color(0xFF0A2000)
val md_theme_light_secondary = Color(0xFF56624B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF5F6EC)
val md_theme_light_onSecondaryContainer = Color(0xFF141E0C)
val md_theme_light_tertiary = Color(0xFF325DA8)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD8E2FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001A42)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFE48672)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFFF8)
val md_theme_light_onBackground = Color(0xFF212A36)
val md_theme_light_surface = Color(0xFFFEFFF8)
val md_theme_light_onSurface = Color(0xFF212A36)
val md_theme_light_surfaceVariant = Color(0xFFF5F6EC)
val md_theme_light_onSurfaceVariant = Color(0xFF44483E)
val md_theme_light_outline = Color(0xFF74796D)
val md_theme_light_inverseOnSurface = Color(0xFFD6F6FF)
val md_theme_light_inverseSurface = Color(0xFF00363F)
val md_theme_light_inversePrimary = Color(0xFF8EDC9A)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF63AF6F)
val md_theme_light_outlineVariant = Color(0xFFC4C8BB)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF8EDC9A)
val md_theme_dark_onPrimary = Color(0xFF163800)
val md_theme_dark_primaryContainer = Color(0xFF245102)
val md_theme_dark_onPrimaryContainer = Color(0xFFBBF293)
val md_theme_dark_secondary = Color(0xFFA3D578)
val md_theme_dark_onSecondary = Color(0xFF1A3700)
val md_theme_dark_secondaryContainer = Color(0xFF285000)
val md_theme_dark_onSecondaryContainer = Color(0xFFBEF291)
val md_theme_dark_tertiary = Color(0xFFAEC6FF)
val md_theme_dark_onTertiary = Color(0xFF002E6A)
val md_theme_dark_tertiaryContainer = Color(0xFF11448F)
val md_theme_dark_onTertiaryContainer = Color(0xFFD8E2FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFF690005)
val md_theme_dark_background = Color(0xFF222529)
val md_theme_dark_onBackground = Color(0xFF5FAD51)
val md_theme_dark_surface = Color(0xFF222529)
val md_theme_dark_onSurface = Color(0xFF5FAD51)
val md_theme_dark_surfaceVariant = Color(0xFF44483E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C8BB)
val md_theme_dark_outline = Color(0xFF33363A)
val md_theme_dark_inverseOnSurface = Color(0xFF222529)
val md_theme_dark_inverseSurface = Color(0xFF5FAD51)
val md_theme_dark_inversePrimary = Color(0xFF63AF6F)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF8EDC9A)
val md_theme_dark_outlineVariant = Color(0xFF44483E)
val md_theme_dark_scrim = Color(0xFF000000)

val playColor = Color(0xFF5FAD51)
val REF = Color(0xFFA6EEFF)

val test1 = Color(0xFF212A36)
val test2 = Color(0xFF7fbe74)
val test3 = Color(0xFF8EDC9A)


val seed = Color(0xFF63AF6F)